#Jailed Players Inventory
jail:
  jailbreak-tp: true  # if true, Teleports players back to jail; if false, displays a warning message.
  keep-inventory: false  # if false, Gives the player a set of items; if true, keeps the original inventory.
  jail-items:           # items given to jailed players when keep-inventory is false
    - item: BAKED_POTATO
      amount: 32
    - item: WATER_BUCKET
      amount: 1
    - item: BREAD
      amount: 16
    # more items can be added

# Blocked commands when jailed
blockedCommands:
  - "tpa"
  - "home"
  - "spawn"
  - "team"
  - "rtp"
  - "tpr"
  - "warp"

# Jail restrictions for actions
# Set to true to allow the action while jailed, false to block the action.
jail-restrictions:
  block-break: false # If false, players cannot break blocks while jailed.
  block-place: false # If false, players cannot place blocks while jailed.
  attack: false      # If false, players cannot attack entities while jailed.
  vehicle-ride: false # If false, players cannot ride vehicles (e.g., boats, minecarts) while jailed.
  ender-pearl: false  # If false, players cannot use ender pearls while jailed.