name: JailPlugin
version: '1.0.0'
main: me.zitemaker.jail.JailPlugin
api-version: '1.13'
author: zitemaker

commands:
  jail:
    description: Jail management command
    usage: /jail setflag <name> <position>
    permission: op