name: Jails
version: ${project.version}
main: com.zitemaker.jails.JailsFree
api-version: '1.21'
author: Zitemaker Studios
softdepend: [SkinsRestorer, PlaceholderAPI]

commands:
  jails:
    description: Main command for jail management
    usage: /jails <subcommand>
    aliases: [j]

  jailsreload:
    description: Reloads the plugin configuration
    usage: /jailsreload
    aliases: [jreload, jr]

  confirmunjail:
    description: Confirm unjail action (backend command)

  cancelunjail:
    description: Cancel unjail action (backend command)

  deljailcf:
    description: Confirm deletion of a jail (backend command)
    usage: /handledeljail <yes|no>
    permission: jails.handledel

permissions:

  jails.setjail:
    description: Allows setting jail locations.
    usage: /setjail <name>
    default: op

  jails.jail:
    description: Allows jailing players.
    usage: /jail <player> <jail name> <reason>
    default: op

  jails.list:
    description: Allows listing all jail locations.
    usage: /jails
    default: true

  jails.unjail:
    description: Allows unjailing players.
    usage: /unjail <player>
    default: op

  jails.duration:
    description: Allows viewing jail durations.
    usage: /jailduration <player>
    default: true

  jails.tempjail:
    description: Allows temporarily jailing players.
    usage: /tempjail <player> <jail name> <duration> <reason>
    default: op

  jails.deljail:
    description: Allows deleting jail locations.
    usage: /deljail <jail name>
    default: op

  jails.handcuff:
    description: Allows handcuffing players.
    usage: /handcuff <player>
    default: op

  jails.unhandcuff:
    description: Allows removing handcuffs.
    usage: /unhandcuff <player>
    default: op

  jails.reload:
    description: Allows reloading the Jails config file.
    usage: /jailsreload
    default: op

  jails.help:
    description: Allows accessing help pages for the Jails plugin.
    usage: /jailshelp
    default: true

  jails.version:
    description: Allows checking the current version of the Jails plugin.
    usage: /jailversion
    default: true