name: JailPlugin
version: '1.0.0'
main: me.zitemaker.jail.JailPlugin
api-version: '1.13'
author: zitemaker


commands:
  jailset:
    description: Set a jail location.
  jail:
    description: Jail a player.
    usage: /jail <player> <jail name> <reason>
    permission: jails.jail
  jails:
    description: List all jail locations.
    usage: /jails
    permission: jails.jails
  unjail:
    description: Unjail a player.
    usage: /unjail <player>
    permission: jails.unjail
  jailduration:
    description: View your or a player's jail duration
    usage: /jailduration <player>
  tempjail:
    description: Temporarily jail a player.
    usage: /tempjail <player> <jail name> <duration> <reason>
    permission: jails.tempjail

  deljail:
    description: Deletes a jail
    usage: /deljail <jail name>
    permission: jailplugin.deljail

  jailed:
    description: Manage jailed players.
    usage: /jailed list
    permission: jails.list
    permission-message: You do not have permission to use this command.
  jailspawn:
    description: Select whether a jailed player will get sent to spawn or their original location after getting unjailed
    usage: /jailspawn <player> <world_spawn/original_location>
    permission: jails.spawn
