name: Jails
version: '1.0.2'
main: me.zitemaker.jail.JailPlugin
api-version: '1.21'
author: zitemaker
softdepend: [WorldEdit, SkinsRestorer]


commands:
  setjail:
    description: Set a jail location.
    usage: /setjail <name>
    permission: jails.setjail
  jail:
    description: Jail a player.
    usage: /jail <player> <jail name> <reason>
    permission: jails.jail
  jails:
    description: List all jail locations.
    usage: /jails
    permission: jails.jails
  unjail:
    description: Unjail a player.
    usage: /unjail <player>
    permission: jails.unjail
  jailduration:
    description: View your or a player's jail duration
    usage: /jailduration <player>
  tempjail:
    description: Temporarily jail a player.
    usage: /tempjail <player> <jail name> <duration> <reason>
    permission: jails.tempjail

  deljail:
    description: Deletes a jail
    usage: /deljail <jail name>
    permission: jailplugin.deljail

  jailed:
    description: Manage jailed players.
    usage: /jailed list
    permission: jails.list
    permission-message: You do not have permission to use this command.

  jailspawn:
    description: Select whether a jailed player will get sent to spawn or their original location after getting unjailed
    usage: /jailspawn <player> <world_spawn | original_location>
    permission: jails.spawn

  jailsetflag:
    description: Set a jail flag using WorldEdit positions.
    usage: /jailsetflag
    permission: jails.setflag

  jaildelflag:
    description: Delete a flag for a jail area.
    usage: /jaildelflag <flagName>
    permission: jails.delflag

  jailflaglist:
    description: Open a GUI to list all flags.
    usage: /jailflaglist
    permission: jails.flaglist

  handcuff:
    description: Handcuff a player to restrict their movement.
    usage: /handcuff <player>
    permission: jails.handcuff

  unhandcuff:
    description: Remove handcuffs from a player.
    usage: /unhandcuff <player>
    permission: jails.unhandcuff

  jailsreload:
    description: Reloads the Jails config file
    usage: /jailsreload
    permission: jails.reload

  jailshelp:
    description: Displays the help pages for the jail plugin
    usage: /jailshelp
    permission: jails.help